language: ruby
rvm:
  - 1.9
  - 2.0
  - 2.1
  - 2.2
  - 2.3.0
  - rbx-2
  - rbx-3.26
  - jruby-19mode
  - jruby-9.0.5
jdk: 
  - openjdk6
  - openjdk7
  - oraclejdk7
  - oraclejdk8
before_install:
  - gem install bundler
