language: ruby
os:
  - linux
  - osx
rvm:
  - 1.9
  - 2.0
  - 2.1
  - 2.2
  - 2.3.0
  - rbx-2
  - rbx-3.26
matrix:
  include:
    - rvm: &jruby_1_7 jruby-19mode
      jdk: openjdk6
    - rvm: *jruby_1_7
      jdk: openjdk7
    - rvm: *jruby_1_7
      jdk: oraclejdk7
    - rvm: *jruby_1_7
      jdk: oraclejdk8
    - rvm: &jruby_9_0 jruby-9.0.5
      jdk: openjdk6
    - rvm: *jruby_9_0
      jdk: openjdk7
    - rvm: *jruby_9_0
      jdk: oraclejdk7
    - rvm: *jruby_9_0
      jdk: oraclejdk8
before_install:
  - gem install bundler
